# config/logrotate-nginx.conf
/var/log/nginx/access.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    su root root
    create 0640 root root
    sharedscripts
    postrotate
        nginx -s reopen
    endscript
}
